# This Dockerfile was generated by the DockerFileGenerator project.
# Created on Mon Feb 08 14:55:28 CET 2016

# Pull base image
FROM java:7

MAINTAINER Pauline "pauline@test.com"

# Update and install
RUN \
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y vim wget curl git maven tomcat7 



# Attach volume
VOLUME /volume/wd

# Create working directory
RUN mkdir -p /local/wd
WORKDIR /local/wd

#Copy sources
COPY /home/m2iagl/fernandez/Documents/idl/DockerFile-Generator/test /testevol

# Generate and copy war
RUN cd testevol//tool/ && mvn clean package -DskipTests && cp target/testevol.war ~/../../var/lib/tomcat7/webapps/

# Run terminal
CMD ["/bin/bash"]